import Image from "next/image";
import Layout from "../components/Layout";
import Head from "next/head";
import profilePic from "../../public/images/profile/developer-pic-1.png";
import AnimatedText from "@/components/AnimatedText";
import Link from "next/link";
import { LinkArrow } from "@/components/Icons";
import TransitionEffect from "@/components/TransitionEffect";

export default function Home() {
  return (
    <>
      <Head>
        <title>Imam Hossain</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className="flex items-center text-dark w-full min-h-screen dark:text-light">
        <Layout className="pt-0 md:p-16 sm:pt-8">
          <div className="flex items-center justify-between w-full lg:flex-col">
            <div className="w-1/2 md:w-full md:justify-center md:flex  ">
              <figure className="relative max-w-sm transition-all duration-300 cursor-pointer filter">
                <a href="#">
                  <Image
                    src={profilePic}
                    alt="COdeBuks"
                    priority
                    sizes="(max-width: 768px) 100vw,
                    (max-width: 1200px) 50vw,
                    50vw"
                    className="h-auto max-w-lg ml-auto lg:hidden md:inline-block md:w-full "
                  />
                </a>
              </figure>
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full  lg:text-center">
              <h1></h1>
              <AnimatedText
                text="IMAM HOSSAIN"
                className="!text-6xl !text-left xl:!text-5xl lg:!text-center lg:!text=6xl md:!text-5xl sm:!text-3xl md:mt-8"
              />
              <AnimatedText
                text="Full stack web developer"
                className="!text-2xl !text-left xl:!text-3xl lg:!text-center lg:!text=4xl md:!text-3xl sm:!text-2xl md:mt-8"
              />

              <p className="my-4 font-medium md:text-sm sm:text-xs text-justify break-words">
                As a skilled full-stack developer, I am dedicated to turning
                ideas into innovative web applications. Explore my latest
                projects and articles, showcasing my expertise in React.js,
                Next.js,TypeScript, Node, MongoDB and web development.
              </p>
              <div className="flex items-center self-start mt-2 lg:self-center">
                <Link
                  href="/ImamCV.pdf"
                  target={"_blank"}
                  className="flex items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border border-solid border-transparent hover:border-dark
                  
                  dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base"
                  download={true}
                >
                  Resume <LinkArrow className="w-6 ml-1" />
                </Link>
                <Link
                  href="mailto:office.imam647@gmail.com"
                  target={"_blank"}
                  className="ml-4 text-lg font-medium capitalize text-dark underline dark:text-light md:text-base"
                >
                  Hire Me
                </Link>
              </div>
            </div>
          </div>
        </Layout>
      </main>
    </>
  );
}
